---
title: "PA 7"
author: "Alex Goodman"
format:
  html:
    self-contained: True
    code-tools: True
    code-fold: True
execute:
  echo: true
  error: true
  message: false
  warning: false
theme: cerulean
---
1.
```{r}
library(tidyverse)
divide_and_round <- function(nums){
  
  my_min <- min(nums, na.rm = TRUE)
  divided <- nums/my_min
  rounded <- round(divided)
}
test <- c(5:10, NA)

ans <- divide_and_round(test)
```
2.
```{r}
no_nines_or_twelves <- function(nums){
  
  check <- !(nums %% 9 == 0 | nums %% 12 == 0)
  
}
test <- c(3:12*5, NA)

ans2 <- no_nines_or_twelves(test)
```
3.
```{r}
every_other <- function(vec, start = 1){
  
  if(start == 2){
  return(vec[seq(2, length(vec), 2)])
    
  } else if(start == 1) {
    return(vec[seq(1, length(vec), 2)])  
  }
  
}
test <- c(1:10)

every_other(test)
every_other(test, start = 2)
```

4.
```{r}
shorten <- function(x, cutoff){
  sum_vec <- cumsum(x)
  values <- which(sum_vec >= cutoff)
  if_else(sum_vec > cutoff, 
          return(x[values]),
          return(x))
  
}
test <- c(11:20)
cutoff <- 23
shorten(test, cutoff)
```


5.
```{r}
my_vec <- c(39, 1.87, 48, 11, 8, 45, 21, 5, 12, 33, 9, 11, 108, 4, 18, 5, 16,
            17, 8, 48, 27, 24, 4, 22, 12, 27, 23, 46, 42, 35, 15, 34, 36, 26,
            18, 10, 18.21, 72.04, 36.9, 41.81, 29, 89.75, 34.03, 20.18, 48.74,
            15.76, 31.86, 83.6, 43.55, 39.99, 23.55, 8.54, 24.71, 22.02, 9.71,
            62.14, 35.46, 16.61, 15.66, 21.29, 30.52, 201.07, 45.81, 7.85,
            30.13, 34.14, 22.62, 10.2, 6.02, 30.12, 10.64, 31.72, 24.57, 14.43,
            43.37, 89.93, 44.72, 51.32, 13.62, 45.56, 22.96, 7.05, 29.99, 41.38,
            26.59, 23.04, 19.82, 50.73, 39.56, 43.79, 30.22, 85.85, 5.78, 78.85,
            29.52, 66.27, 44.06, 27.28, 24.43, 64.32, 3.35, 67.45, 46.72, 48.44,
            48.65, 33.3, 40.28, 19.04)

my_vec <- every_other(my_vec, start = 2)
# Should have 54 elements! 

my_vec <- divide_and_round(my_vec)

my_vec <- every_other(my_vec, start = 1)
# Should have 27 elements!

my_vec <- shorten(my_vec, 350)
# Should have 12 elements!

my_vec <- my_vec[no_nines_or_twelves(my_vec)]
# Should have 6 elements! 

my_vec <- sort(my_vec)

my_vec
```








